Description: >
  This template creates an IAM user and an access key for the user. The credentials are sent via email to the specified address.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Create IAM User for using a specific cloudX Environment
        Parameters:
          - UserName
          - EnvironmentName
          - EmailAddress
    ParameterLabels:
      UserName:
        default: CloudX User Name (the IAM user will be named cloudX-<EnvironmentName>-<UserName>)
      EnvironmentName:
        default: CloudX Environment name
      EmailAddress:
        default: Email address to receive credentials

Parameters:
  UserName:
    Type: String
    Default: username
    Description: 'Name of the CloudX user (without prefix)'

  EnvironmentName:
    Type: String
    Default: 'OTA'
    Description: 'Name of the CloudX Environment (must match the EnvironmentName used in cloudX-Environment template)'

  EmailAddress:
    Type: String
    Description: Email address where credentials will be sent
    AllowedPattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    ConstraintDescription: Must be a valid email address

Resources:
  CloudXUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "cloudX-${EnvironmentName}-${UserName}"
      Groups:
        - !Sub '{{resolve:ssm:/cloudX/${EnvironmentName}/IAMGroupName}}'
      Tags:
        - Key: 'ez2:ops:contact:email'
          Value: !Ref EmailAddress

  CloudXUserAccessKey:
    Type: AWS::IAM::AccessKey
    DependsOn: CloudXUser
    Properties:
      UserName: !Sub "cloudX-${EnvironmentName}-${UserName}"

  CloudXUserAccessKeySecret:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /cloudX/${EnvironmentName}/${UserName}/CloudXUserAccessKeySecret
      Type: String
      Value: !GetAtt CloudXUserAccessKey.SecretAccessKey

  CloudXUserAccessKeyId:  
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /cloudX/${EnvironmentName}/${UserName}/CloudXUserAccessKeyId
      Type: String
      Value: !Ref CloudXUserAccessKey
